# Generated by Django 5.0.6 on 2024-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPO_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo_path', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('price_band', models.CharField(blank=True, max_length=255, null=True)),
                ('open', models.CharField(blank=True, max_length=255, null=True)),
                ('close', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_size', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('ipo_price', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_price', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_gain', models.CharField(blank=True, max_length=255, null=True)),
                ('cmp', models.CharField(blank=True, max_length=255, null=True)),
                ('current_return', models.CharField(blank=True, max_length=255, null=True)),
                ('rhp', models.TextField(blank=True, null=True)),
                ('drhp', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ipo',
            name='listing_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='listing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
